### PR TITLE
Upgrade to react v15+

### PR DESCRIPTION
**Pull request by pinqy520**
- update dependencies
- add `yarn.lock` to `.gitignore`
- add source map for webpack dev
- works in react v15+

### CODE REVIEW

**Comment by reimertz** [comment]
Wow, great job @pinqy520

**Comment by pinqy520** [comment]
....there are some error when the ListView scrolls. I will fix it tomorrow. Don't merge...

**Comment by pinqy520** [comment]
image

Done~!

**Comment by tconroy** [comment]
this looks great.. Any plans to merge this in?

**Comment by pinqy520** [comment]
ping? @tuxracer

**Comment by tuxracer** [comment]
@pinqy520 awesome work!! I'm not with Flipboard anymore but @tleewu or @hiirene may be able to help with this

**Comment by pinqy520** [comment]
Thanks~! @tuxracer

**Comment by athrunsun** [comment]
Guys, are we still waiting for something or someone to merge this?

**Comment by tconroy** [comment]
@athrunsun looking at the commit log it seems @tleewu tried bumping up to 15 back in September but reverted. Why not just merge this PR which seems to be working? :)

**Comment by tconroy** [comment]
Thank you @hiirene! 🍻

**Comment by hiirene** [comment]
Thank @pinqy520 actually :-) and @tuxracer,  FYI @tuxracer has updated the package to include this fix.

**Pull request merged**
