### PR TITLE
Add ScrollView component

### PR DESCRIPTION
**Pull request by mbrgm**
This is similar to the ListView component but allows each item to have its
own individual height. For performance reasons, the items and item heights
are passed at component creation time instead of using a getter function.

I also formatted the README to not break the popular 80 column limit for better
readability when not using soft wrapping.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
@mbrgm Why did you close this PR?

**Comment by mbrgm** [comment]
@SalahAdDin 
* I wanted to get rid of my long-time pending PRs to regain some overview
* Not expecting this to be merged anytime soon, as it's open for more than 2 years now
* Not using react-canvas anymore for a long time now

**Comment by SalahAdDin** [comment]
@mbrgm So, what are you doing instead this package?

**Comment by mbrgm** [comment]
@SalahAdDin Not doing much mobile dev anymore.

**Pull request closed without merging**
