### PR TITLE
Support 0.14.0-beta1

### PR DESCRIPTION
**Pull request by slorber**
I think this is required to use the new beta version.
See also https://github.com/gaearon/react-hot-api/issues/18

### CODE REVIEW

**Comment by mjohnston** [comment]
We should probably make this "0.14-beta-* and up".

**Comment by slorber** [comment]
@mjohnston yes

Take a look here:
https://github.com/facebook/react/issues/4542

You can use something like:

```
"peerDependencies": {
    "react": "^0.13.0 || ^0.14.0-alpha"
  },
```

**Comment by gre** [comment]
sounds like we can make a range that accepts 0.14.0 now that it is released ;)

```json
    "react-native": ">=0.13.0 <0.15.0"
```

**Comment by gre** [comment]
also I don't think this PR is complete. Ideally we should also focus all warning (a lot of `Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly.`)

**Comment by mjohnston** [comment]
@gre Agreed, we should make the necessary changes to move onto 0.14.

**Comment by gre** [comment]
i've provided another PR https://github.com/Flipboard/react-canvas/pull/115

**Pull request closed without merging**
