### PR TITLE
Chore/add warning to readme

### PR DESCRIPTION
**Pull request by Scarysize**
It's a bit frustrating to setup everything and then find out that recent react versions aren't supported. Hope this warning helps save some time.

### CODE REVIEW

**Comment by framerate** [comment]
@Scarysize  Ugh, this doesn't work with recent React? Is this project abandoned or is there somewhere this kind of stuff is talked about?

**Comment by f1ana** [comment]
Woof

**Comment by Scarysize** [comment]
@framerate I have no idea how actively maintained this is or if support for react v15 is being worked on.

**Comment by framerate** [comment]
It looks like the authors no longer work at @flipboard. I'm investigating a fork to see if the community and I can maybe breathe life back into it?

**Comment by tleewu** [comment]
@framerate I've just updated the repo to support React 15.0.0 and I've bumped it to version 1.2.2. I'm relatively new to React Canvas, but I'm beginning to learn all of its beautiful complexities and I expect to actively maintain it.

**Comment by framerate** [comment]
@tleewu You just became my favorite person! Thank you!

I may be interested in helping with some improvements if you guys are interested. Mainly I'm curious why we can't use custom fonts (more maybe that's incorrect in the readme?) and if we can make the ListView takes items of different heights.

Thoughts?

**Comment by tleewu** [comment]
@framerate ahhh I had to revert back to v0.14.0 - I read some of the comments by @gre and I'm going to take a deeper look. Sorry about that!

Regarding custom fonts, I'll take a look and get back!

**Pull request closed without merging**
