### PR TITLE
Use React Hot Loader for live-editing examples

### PR DESCRIPTION
**Pull request by gaearon**
Don't know if you're into that, but this gives you [React Hot Loader](http://gaearon.github.io/react-hot-loader/) powered live-editing for the examples. I noticed it doesn't update `<Text>` but a lot of other components (in examples and source) auto-update fine.

It's still `npm start`.

### CODE REVIEW

**Comment by gaearon** [comment]
Lol, I can tweak layout algorithm live without reloading because it is stateless and components pick up the changes.

screen shot 2015-02-11 at 0 48 19

**Comment by mjohnston** [comment]
This is very cool. Touch events appear to also be broken after an update though. Text metrics are cached which could be the reason why you're not seeing <Text> changes reflected.

**Comment by gaearon** [comment]
I'll take a look, thanks.

Where does text metric caching happens? I'm calling `forceUpdate` after hot-replacing all methods, is this not enough?

**Comment by mjohnston** [comment]
Now that I think about it, this is likely due to the backing stores (cached off-screen canvases) not being invalidated when you call `forceUpdate`. Is there a way to hook into the hot loader's update mechanism and execute additional code?

**Comment by gaearon** [comment]
@mjohnston 

There is no really official way to do that because I want to resist adding custom API as long as it makes sense. :-) Can you point me to where the caching happens?

There are a couple of ways to hook into hot loading update for components:

* Do some kind of invalidation in `componentDidUpdate` and have a restrictive `shouldComponentUpdate`. Hot Loader won't care about `shouldComponentUpdate` result.

* You can use `module.hot` as a check for whether hot loading is enabled, and if it's true, add some additional logic to `componentWillUpdate` or `componentDidUpdate`. For example, in react-jss I see [the styles provided to mixin in closure don't match the ones saved on component instance, which means they got hot-updated](https://github.com/jsstyles/react-jss/blob/master/index.js#L63). I know it's kind of hackish.

It'll be easier to tell what can be done if you point me to where the caching happens!

**Pull request closed without merging**
