### PR TITLE
Add support for various mouse events

### PR DESCRIPTION
**Pull request by garbles**
`react-canvas` is exactly the thing I've been looking for, but it doesn't have support for mouse events yet. This branch adds support for various mouse events. Need to create an example/write tests to make sure that they all work.

Very interested in feedback/suggestions.

### CODE REVIEW

**Comment by zh221** [comment]
Yes!it is important

**Comment by darkyen** [comment]
+1

**Comment by brentvatne** [comment]
@mjohnston - any thoughts on this PR?

**Comment by garbles** [comment]
@brentvatne I'm closing since I don't have an interest in working on this any further.

**Comment by mjohnston** [comment]
Sorry I was late to respond on this one. I'd like to eventually move the events system to something closer to React Native's model (or use it wholesale if/when it's merged into React mainline), so I've been hesitant to make significant changes that touch this area.

**Pull request closed without merging**
